security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
    firewalls:
        main:
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication
    access_control:
        - { path: ^/user/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_ADMIN }

# https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#getting-started
# https://symfonycasts.com/screencast/symfony-rest4/jwt-guard-authenticator
