# https://symfonycasts.com/screencast/symfony-security/firewalls-authenticator
security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
#    enable_authenticator_manager: true
    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication
    access_control:
        - { path: ^/user/login, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER




# https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#getting-started
# https://symfonycasts.com/screencast/symfony-rest4/jwt-guard-authenticator
