#https://starkovden.github.io/openapi-tutorial-overview.html
openapi: "3.0.0"
info:
  description: "This is a small app for test mongo DB, openapi + redoc + php8 and symfony 5.1"
  version: "1.0.1"
  title: "Mongo app"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "excort13@mail.ru"
  license:
    name: "with out license"
servers:
  - url: "http://127.0.0.1:81"
    description: For local servers
tags:
  - name: "User"
    description: "Operations about user"
  - name: "Vehicle"
    description: "Operations about vehicle"
parameters:
  page:
    description: The page number (use from second page)
    in: path
    name: page
    required: no
    type: integer
  manufacturer:
    description: The page number (use from second page)
    in: query
    name: manufacturer
    required: no
    type: string
consumes:
  - application/json
produces:
  - application/json
components:
  securitySchemes:
    global:
      in: header
      name: X-AUTH-TOKEN
      type: apiKey
      description: API key to authorize requests
security:
  - global: []
paths:
  /user/login:
    post:
      tags:
        - "User"
      summary: "Logs user"
      description: "Logs user into the system"
      operationId: "user_login"
      parameters:
        - description: "The user name for login"
          name: "body"
          in: "body"
          required: true
          schema:
            properties:
              username:
                description: User's email address
                maxLength: 128
                type: string
              password:
                description: User's email address
                maxLength: 128
                type: string
            required:
              - action
            type: object
  /vehicle/list/{page}:
    get:
      tags:
        - "Vehicle"
      summary: "Vehicle list"
      description: "Get vehicle list with pagination"
      operationId: "vehicle_list"
      parameters:
        - $ref: '#/parameters/page'
        - $ref: '#/parameters/manufacturer'
