version: '3.7'
networks:
    mongo:
        name: mongo_network
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.221.0/28

volumes:
    postgres:
    redis:

services:
    nginx:
        image: nginx:1.19.0
        restart: on-failure
        volumes:
            - './:/usr/src/app'
            - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - 81:80
        depends_on:
            - php
        networks:
            - mongo
        container_name: mng_nginx
    php:
        hostname: "socket-php"
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        restart: on-failure
        networks:
            - mongo
        container_name: "mng_php"
        volumes:
            - ./:/usr/src/app
            - ./docs/swagger:/usr/src/docs
        working_dir: /usr/src/app
        ports:
            - "127.0.0.1:9000:9000"
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
            DOMAIN: ${DOMAIN}
#        logging:
#            driver: "json-file"
#            options:
#                max-size: "1024k"
#                max-file: "2"
    redoc:
        container_name: "mng_redoc"
        image: redocly/redoc
        restart: on-failure
        ports:
            - 8890:80
        volumes:
            - ./docs/swagger/:/usr/share/nginx/html/doc/
        environment:
            SPEC_URL: ./doc/swagger.yaml
    mongo:
        container_name: "mng_mongo"
        image: mongo
        restart: on-failure
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        #        volumes:
        #            - ./docker/mongo:/data/db
        networks:
            - mongo
